# yaml-language-server: $schema=https://raw.githubusercontent.com/wundergraph/cosmo/router%400.139.0/router/pkg/config/config.schema.json
version: "1"

log_level: "info"

modules:
  auth:
    enabled: true
  cacheControl:
    enabled: false

cache_control_policy:
  enabled: true

overrides:
  subgraphs:
    picks2:
      routing_url: https://server-subgraph.qa.picks.cbssports.cloud/graphql
      subscription_url: http://router:3002/graphql/ws
      subscription_protocol: ws
      subscription_websocket_subprotocol: graphql-ws
    picks-legacy:
      routing_url: https://legacy-subgraph.qa.picks.cbssports.cloud/graphql
      subscription_url: http://router:3002/graphql/ws
      subscription_protocol: ws
      subscription_websocket_subprotocol: graphql-ws

telemetry:
  service_name: "picks-router-local"
  metrics:
    prometheus:
      enabled: true
      path: "/metrics"
      listen_addr: "127.0.0.1:8088"
      exclude_metrics: []
      exclude_metric_labels: []
